stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

build:
  stage: build
  image: docker:latest
  services:
    - docker:24.0.5-dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main

test:
  stage: test
  image: docker:latest
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Running conditional tests..."
    - if [ -f "requirements.txt" ]; then
        docker run --rm $DOCKER_IMAGE python -c "import flask; print('Flask is installed')";
      else
        echo "No requirements.txt found, skipping tests.";
      fi
  only:
    - main


deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:24.0.5-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Deploying application..."
    - docker pull $DOCKER_IMAGE
    - docker run -d -p 5000:5000 --name my_web_app $DOCKER_IMAGE
    - echo "Application deployed and running at http://localhost:5000"
  only:
    - main